language: python
python:
  - 3.5.2

install:
  - pip install requests
  - pip install pymysql
  - pip install xmltodict
  - pip install redis

script:
  - python Spider.py

branches:
  only:
    - master
